# version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - frontend-net
    depends_on:
      backend:
        condition: service_started
    cpus: '0.50'
    mem_limit: 256M
    mem_reservation: 128M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"] 
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - VUE_APP_API_URL=http://backend:8081/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - backend-net
      - frontend-net
    cpus: '0.50'
    mem_limit: 512M
    mem_reservation: 256M
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    read_only: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge
