version: '3.8' # в новых версиях Docker Compose можно не указывать
services:
  front:
    build: ./frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
    restart: unless-stopped
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
  redis_data: