name: trivy

on:
  push:
    branches: [ "main" ]

jobs:
  scan_vulnerabilities:
    name: Run Trivy vulnerability scanner
    runs-on: ubuntu-latest 
    needs: build_and_push_to_docker_hub
    steps:
        - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }} 

        - name: Scaning Backend image
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: ${{ secrets.DOCKER_USER }}/cloud-services-engineer-docker-project-sem2-backend:latest
          format: table
          severity: CRITICAL,HIGH
          vuln-type: os,library
          exit-code: 1
          ignore-unfixed: true
          
        - name: Scan Frontend image
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: ${{ secrets.DOCKER_USER }}/cloud-services-engineer-docker-project-sem2-frontend:latest
          format: table
          severity: CRITICAL,HIGH
          vuln-type: os,library
          exit-code: 1
          ignore-unfixed: true
